spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/neodb
    username: root
    password: 1928374650

  liquibase:
    change-log: db/changelog/main-changelog.xml